/* Task 2: CRUD Operations
Write SQL queries for the following operations:
1. Insert a new product with the following details: Product Name: "Laptop", Price: 1000.00,
Stock Quantity: 50.
2. Update the stock quantity of the product with product_id = 3 to 75.
3. Delete the order with order_id = 10 and its associated order items.
4. Retrieve the customer's first and last names who placed the order with order_id = 5.
5. Calculate the total revenue generated by each product (sum of subtotals from order
items). */

--1. Insert a new product

INSERT INTO Product (product_name, price, stock_quantity)
VALUES ('Laptop', 1000.00, 50);

--2. Update the stock quantity

UPDATE Product
SET stock_quantity = 75
WHERE product_id = 3;

--3. Delete order_id = 10
BEGIN;
-- Delete elements from OrderItem with order_id = 10
DELETE FROM OrderItem
WHERE order_id = 10;

-- Delete elements from Order with order_id = 10
DELETE FROM Orders
WHERE order_id = 10;

COMMIT;

--4. Retrieve customer's first and last names who placed an order
SELECT C.first_name, C.last_name
FROM Customer C
INNER JOIN Orders O ON C.customer_id = O.customer_id
WHERE O.order_id = 5;

--5. Calculate the total revenue generated by each product

SELECT P.product_id, P.product_name, SUM(OI.subtotal) AS total_revenue
FROM Product P
LEFT JOIN OrderItem OI ON P.product_id = OI.product_id
GROUP BY P.product_id, P.product_name;