/* Task 3: Stored Procedures
Create a stored procedure that calculates and returns the total revenue generated by a specific
customer. */

--Create Delimtter
DELIMITER //

CREATE PROCEDURE CalculateCustomerRevenue(IN customerID INT, OUT totalRevenue DECIMAL(10, 2))
BEGIN
    SELECT SUM(oi.subtotal)
    INTO totalRevenue
    FROM Orders O
    JOIN OrderItem OI ON o.order_id = oi.order_id
    WHERE O.customer_id = customerID;
END;
//

DELIMITER ;
